function(download_netusbcam NETUSBCAM_LIB_VAR NETUSBCAM_INCLUDE_DIR_VAR)
  if(NOT UNIX)
    message(FATAL_ERROR "Downloading NETUSBCAM Library for non-linux system is currently not supported.")
  endif()

  set(NETUSBCAM_LIB "${CATKIN_DEVEL_PREFIX}/${CATKIN_PACKAGE_LIB_DESTINATION}/libNETUSBCAM.so")
  set(NETUSBCAM_INCLUDE_DIR "${CATKIN_DEVEL_PREFIX}/${CATKIN_PACKAGE_INCLUDE_DESTINATION}")
  set(NETUSBCAM_DOWNLOAD_SCRIPT "${PROJECT_SOURCE_DIR}/cmake/download_netusbcam.py")
  execute_process(
    COMMAND ${NETUSBCAM_DOWNLOAD_SCRIPT} ${NETUSBCAM_LIB} ${NETUSBCAM_INCLUDE_DIR}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})

  set(${NETUSBCAM_LIB_VAR} ${NETUSBCAM_LIB} PARENT_SCOPE)
  set(${NETUSBCAM_INCLUDE_DIR_VAR} ${NETUSBCAM_INCLUDE_DIR} PARENT_SCOPE)
endfunction()
